### ISSUE TITLE
Cant download files

### ISSUE THREAD

**Issue by Afterplay159** [AeonLucid/Prospect#11]
i tryed to install it but didnt work, it says that it isnt avaliable for my account but i played the cycle before

![imagem_2024-11-17_220249144](https://github.com/user-attachments/assets/f0628caf-751f-42dd-8733-c43064268f88)

**Comment by xiaodong0627** [comment]
之前测试服体验的时候，申请了测试服的账号

**Comment by Kajek777** [comment]
I think this is happening because the playtest app is not avaliable for download anymore, even for those who own it

**Comment by xiaodong0627** [comment]
也是有可能的，现在没有办法玩嘛？好想玩

**Comment by Afterplay159** [comment]
I was wondering if it was possible using the normal version instead the playtest

**Comment by xiaodong0627** [comment]
能不能玩单机版，离线游玩

**Comment by xiaodong0627** [comment]
可以离线游玩的话，也是可以的

**Comment by xiaodong0627** [comment]
有什么办法可以玩单机版本嘛，改成一个单机游戏，我觉得我还是会喜欢

**Comment by AeonLucid** [comment]
You can't download the game from Steam anymore, you must find the game through other means.
Anyways this server is incomplete and even finding the game won't allow you to play without heavily contributing to the server source code.

**Comment by xiaodong0627** [comment]
> 您无法再从 Steam 下载游戏，您必须通过其他方式找到游戏。无论如何，这个服务器是不完整的，即使找到游戏也不允许你在不对服务器源代码做出重大贡献的情况下玩。

不需要联机游玩，只玩单人模式可以嘛

**Comment by Afterplay159** [comment]
> You can't download the game from Steam anymore, you must find the game through other means. Anyways this server is incomplete and even finding the game won't allow you to play without heavily contributing to the server source code.

I though about installing in the same way but using the normal version, instead of the playtest, would it be possible? if yes, what do i need to change?

**Comment by xiaodong0627** [comment]
有没有源码提供一下
