### ISSUE TITLE
Got depot key for 1600361 result: Blocked

### ISSUE THREAD

**Issue by LuoYouSeng** [AeonLucid/Prospect#4]
There is something at the first stage
I download the depotdownloader and try to install the cycled with the code given in readme
Then the console display download failed with the info  "Got depot key for 1600361 result: Blocked"
I would like to know how to solve this issues
![image](https://github.com/AeonLucid/Prospect/assets/71080298/e4d44f06-1c4a-444b-a204-91651ab40745)

**Comment by Kajek777** [comment]
That is happening probably because that depot is from the The Cycle Playtest app, which is no longer available for download, even for people who used to be in the closed beta
![image](https://github.com/AeonLucid/Prospect/assets/72323591/0e20cdcc-a2db-49de-904e-7b8d3b91c7e4)

**Comment by LuoYouSeng** [comment]
thank you for your replying.
